---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unet-mask
spec:
  selector:
    matchLabels:
      run: unet-mask
  replicas: 1
  template:
    metadata:
      labels:
        run: unet-mask
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: shared
          hostPath:
            path: /mnt/kubernetes/data/unet-mask
            type: Directory
        - name: data
          hostPath:
            path: /root/datasets
            type: Directory
        - name: models
          hostPath:
            path: /mnt/ML
            type: Directory
      containers:
      - name: unet-mask
        image: containers.endev.lt/unet:latest
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: models
          mountPath: /ML
        - name: data
          mountPath: /data/datasets
        - name: shared
          mountPath: /data
        ports:
        - containerPort: 80
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/sh"]
        args:
            - -c
            - >-
                jupyter notebook --no-browser --ip=0.0.0.0 --port=80 --allow-root --NotebookApp.token= --notebook-dir='/data'
      imagePullSecrets:
        - name: containers.endev.lt.regcred
      nodeSelector:
        mlWork: gpu1
---
apiVersion: v1
kind: Service
metadata:
  name: unet-mask
  labels:
    run: unet-mask
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30933
  selector:
    run: unet-mask
